//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogproje.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class makale
    {
        public int Id { get; set; }
        public string makale1 { get; set; }
        public string baslik { get; set; }
        public string makaledetay { get; set; }
        public string resim { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> kategoriId { get; set; }
    
        public virtual kategori kategori { get; set; }
    }
}
